import type { Metadata } from 'next'
import { CookiesProvider } from 'next-client-cookies/server'
import { NextIntlClientProvider } from 'next-intl'
import { Inter } from 'next/font/google'
import { NextAuthProvider } from '../NextAuthProvider'
import '../globals.css'
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  let messages
  try {
    messages = (await import(`../../../messages/${locale}.json`)).default
  } catch (error) {
    console.error(error)
  }

  console.log({ locale })

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <CookiesProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <NextAuthProvider>{children}</NextAuthProvider>
          </NextIntlClientProvider>
        </CookiesProvider>
      </body>
    </html>
  )
}
